# Generated by Django 3.1.7 on 2021-07-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210606_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='suscriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_pago', models.IntegerField(choices=[[0, 'CREDITO'], [1, 'DEBITO'], [2, 'TARJETA DIGITAL'], [3, 'PAYPAL']])),
                ('aviso', models.IntegerField(choices=[[0, 'SI'], [1, 'NO']])),
                ('monto_donation', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
