# Generated by Django 3.1.7 on 2021-07-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210710_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='oferta',
            field=models.IntegerField(),
        ),
    ]
